# Default values for backend.
backend:
  replicaCount: 1
  image: "mdriyazali254362028/todo_backend:v1.0"
  env:
    MONGO_URL: "mongodb://username:password@mongo:27017/todos"
  service:
    type: ClusterIP
    port: 3001

mongo:
  image: "mongo:4.2"
  env:
    MONGODB_INITDB_ROOT_USERNAME: "username"
    MONGODB_INITDB_ROOT_PASSWORD: "password"
  service:
    type: ClusterIP
    port: 27017
