backend:
  image: mdriyazali254362028/todo_backend:latest
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3001
  env:
    MONGO_URL: mongodb://mongo:27017/todos
frontend:
  image: mdriyazali254362028/todo_frontend:latest
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3000
  env:
    REACT_APP_API_URL: http://backend:3001/api
mongo:
  image: mongo
  service:
    type: ClusterIP
    port: 27017
  env:
    MONGODB_INITDB_ROOT_USERNAME: username
    MONGODB_INITDB_ROOT_PASSWORD: password
